# Raise command timeout for git prompts in big repos
command_timeout = 1000

[character]
success_symbol = "[\\$](bold purple)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[|](bold blue)"

[directory]
truncate_to_repo = false
style = "blue"
truncation_length = 8
truncation_symbol = ".../"

[git_branch]
style = "dimmed white"

[git_status]
format = '([$all_status]($style) )([$ahead_behind](blue) )'
diverged = "↓↑"
behind = "↓"
ahead = "↑"

[nix_shell]
format = "via [$name \\[$state\\]]($style) "
impure_msg = "i"
pure_msg = "p"

[cmd_duration]
format = "[$duration]($style) "

[battery]
disabled = true

[python]
disabled = false
symbol = "python "

[java]
disabled = true

[package]
disabled = true

[rust]
symbol = "rust "

[env_var.VAULT_STATUS]
style = "bold red"

[custom.nix_system]
command = "nix-system-info"
format = "for [$symbol($output )]($style)"
extensions = ["nix"]
